### PR TITLE
0.4

### LINKED ISSUE #70: Match background color and Logo Banner with Console
Right now console and frontend look slightly different. See here:
https://fastsurvey.de/empicano/one
https://console.fastsurvey.de/login

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
**Big stuff:**
- [x] #73 
- [x] #62 
<br/>

**Small stuff:**

- [x] #70 
- [x] #65 
- [x] #71
- [x] #66
- [x] #75

### CODE REVIEW

**Comment by dostuffthatmatters** [comment]
@empicano 

I have deployed the latest version on https://dev.fastsurvey.de. It uses the `api.dev.fa...` backend.
Have a look at it and write issues/give feedback if you want :)

**Comment by empicano** [comment]
Very good work, dark mode is easy on the eyes! 👌

In dark mode the red and greens seem a bit out of place, I can't pinpoint why, though 😄 

You could simplify the button between light/dark mode by using a simple ☀️/🌛 button and selecting the one specified by the browser (now "auto") on page load.

**Review by empicano — APPROVED** [review]

**Comment by dostuffthatmatters** [comment]
> Very good work, dark mode is easy on the eyes! 👌
> 
> In dark mode the red and greens seem a bit out of place, I can't pinpoint why, though 😄
Yes, I will refine the dark colors with time :) but as already mentioned - better releasing it somewhat ok looking, than only bright.

> You could simplify the button to choose between light/dark mode by using a simple ☀️/🌛 button and selecting the one specified by the browser (now "auto") on page load.
I don't have icons for sun and moon yet, and emojis looked a bit out of place there. But icon could be better 👍🏼

**Comment by empicano** [comment]
> Yes, I will refine the dark colors with time :) but as already mentioned - better releasing it somewhat ok looking, than only bright.

You're very right about that 👍

> I don't have icons for sun and moon yet, and emojis looked a bit out of place there. But icon could be better 👍🏼

Didn't mean to criticize the design. Just wanted to note that a button with only light/dark would fulfill the same function as the current one with three options if you preselect the preferred option specified by the browser 😋

**Comment by dostuffthatmatters** [comment]
> Didn't mean to criticize the design. Just wanted to note that a button with only light/dark would fulfill the same function as the current one with three options if you preselect the preferred option specified by the browser 😋

Reducing the number of buttons is a good thing! :D However, if the user wants to switch from "alway light" to "choose automatic from system", with only two buttons there is no way of doing this. Right now it stores the state "light"|"auto"|"dark" in a cookie.

There could be two "checkbox" buttons (where selecting one, deselects the other and deselecting one (none of them active) will switch to "auto" mode. But I think this logic is far more complex than just having three buttons.

Many websites do this with two buttons, but as said before: I want to store the state in a cookie AND with two buttons there is no easy way of switching to auto again other than removing the cookie or letting it expire.

Much ado about nothing 😄

**Comment by dostuffthatmatters** [comment]
@empicano 

I have deployed a few updates. See https://dev.fastsurvey.de/blueberry/complex/form for example.
* I have desaturated the colors on the validation messages
* The client now validates the basic email regex (`^.+@.+$`)
* You can now set the apiUrl as well as the console, this should point to

Do those changes work for you?

Here you can see the old colors again: https://commit-d96675b---frontend-dev-gz5l57j4mq-ew.a.run.app/blueberry/complex/form

**Comment by empicano** [comment]
Thanks for the documentation, that helps a lot! 💯 

As for the colors I just played around with them myself a bit, that's difficult, so good work! 😎 Maybe a tactic for dark mode (someday) could be to use a new color scheme so that you don't have to invert the colors yourselves, such that:

`bg-yellow-100 text-yellow-800 dark:bg-yellow-700 dark:text-yellow-50`

becomes:

`light-bg-yellow-100 light-text-yellow-800 dark:dark-bg-yellow-100 dark:dark-text-yellow-800`

or something similar. Just an idea, though, I think for the moment that's perfect, we don't need complicated for now 😄

**Comment by dostuffthatmatters** [comment]
Yes, I will continue to improve the colors and the design! just allocating resources elsewhere as you might have guessed :D

**Pull request merged**
